/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.defaultsm;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IDefaultSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseMoney50centsButton();
		
		public void raiseMoney25centsButton();
		
		public void raiseMoney10centsButton();
		
		public void raiseCoffeeButton();
		
		public boolean isRaisedMakeCoffee();
		
		public boolean isRaisedUpdateSolde();
		
		public boolean isRaisedResetSolde();
		
		public boolean isRaisedTakeCoffee();
		
		public boolean isRaisedCleaningMachine();
		
		public boolean isRaisedMachineReady();
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onMakeCoffeeRaised();
		public void onUpdateSoldeRaised();
		public void onResetSoldeRaised();
		public void onTakeCoffeeRaised();
		public void onCleaningMachineRaised();
		public void onMachineReadyRaised();
		}
	
	public SCInterface getSCInterface();
	
}
