/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.defaultsm;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IDefaultSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseMoney50centsButton();
		
		public void raiseMoney25centsButton();
		
		public void raiseMoney10centsButton();
		
		public void raiseCoffeeButton();
		
		public void raiseTeaButton();
		
		public void raiseExpressoButton();
		
		public void raiseSoupButton();
		
		public void raiseBipButton();
		
		public void raiseCancelButton();
		
		public void raiseIcedTeaButton();
		
		public boolean isRaisedUpdateSolde();
		
		public boolean isRaisedTakeBeverage();
		
		public boolean isRaisedCleaningMachine();
		
		public boolean isRaisedMachineReady();
		
		public boolean isRaisedMakeCoffee();
		
		public boolean isRaisedMakeTea();
		
		public boolean isRaisedMakeExpresso();
		
		public boolean isRaisedMakeSoup();
		
		public boolean isRaisedMakeIcedTea();
		
		public boolean isRaisedCancelPreparation();
		
		public boolean isRaisedTimePreparation();
		
		public boolean isRaisedAskCoffee();
		
		public boolean isRaisedAskTea();
		
		public boolean isRaisedAskExpresso();
		
		public boolean isRaisedAskSoup();
		
		public boolean isRaisedAskIcedTea();
		
		public boolean isRaisedPayByNFC();
		
		public boolean isRaisedCancelTransaction();
		
		public boolean isRaisedResetSliders();
		
		public boolean isRaisedValidatePayment();
		
		public double getSolde();
		
		public void setSolde(double value);
		
		public boolean getPaymentCard();
		
		public void setPaymentCard(boolean value);
		
		public boolean getPaymentDone();
		
		public void setPaymentDone(boolean value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onUpdateSoldeRaised();
		public void onTakeBeverageRaised();
		public void onCleaningMachineRaised();
		public void onMachineReadyRaised();
		public void onMakeCoffeeRaised();
		public void onMakeTeaRaised();
		public void onMakeExpressoRaised();
		public void onMakeSoupRaised();
		public void onMakeIcedTeaRaised();
		public void onCancelPreparationRaised();
		public void onTimePreparationRaised();
		public void onAskCoffeeRaised();
		public void onAskTeaRaised();
		public void onAskExpressoRaised();
		public void onAskSoupRaised();
		public void onAskIcedTeaRaised();
		public void onPayByNFCRaised();
		public void onCancelTransactionRaised();
		public void onResetSlidersRaised();
		public void onValidatePaymentRaised();
		}
	
	public SCInterface getSCInterface();
	
}
