/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.defaultsm;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.List;

public interface IDefaultSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseMoney50centsButton();
		
		public void raiseMoney25centsButton();
		
		public void raiseMoney10centsButton();
		
		public void raiseCoffeeButton();
		
		public void raiseTeaButton();
		
		public void raiseExpressoButton();
		
		public void raiseSoupButton();
		
		public void raiseBipButton();
		
		public void raiseCancelButton();
		
		public void raiseIcedTeaButton();
		
		public boolean isRaisedUpdateSolde();
		
		public boolean isRaisedTakeBeverage();
		
		public boolean isRaisedCleaningMachine();
		
		public boolean isRaisedMachineReady();
		
		public boolean isRaisedBeveragePreparation();
		
		public boolean isRaisedBeverageChoice();
		
		public boolean isRaisedCancelPreparation();
		
		public boolean isRaisedPayByNFC();
		
		public boolean isRaisedCancelTransaction();
		
		public boolean isRaisedResetSliders();
		
		public boolean isRaisedValidatePayment();
		
		public boolean isRaisedTurnOnWaterHeating();
		
		public boolean isRaisedPlacePod();
		
		public boolean isRaisedPlaceTeaBag();
		
		public boolean isRaisedGrindGrains();
		
		public boolean isRaisedPlaceCup();
		
		public boolean isRaisedPackGrains();
		
		public boolean isRaisedWaitTemperature();
		
		public boolean isRaisedFlowWater();
		
		public boolean isRaisedAddSugar();
		
		public boolean isRaisedWaitingInfusion();
		
		public boolean isRaisedTakeChange();
		
		public boolean isRaisedRemoveTeaBag();
		
		public boolean isRaisedFlowWaterOK();
		
		public boolean isRaisedSugarOK();
		
		public boolean isRaisedGrainPackingOK();
		
		public boolean isRaisedWaterTempOK();
		
		public boolean isRaisedTeaBagOK();
		
		public boolean isRaisedPodOK();
		
		public boolean isRaisedGrainCrushingOK();
		
		public boolean isRaisedWaterHeatingOK();
		
		public boolean isRaisedCupOK();
		
		public double getSolde();
		
		public void setSolde(double value);
		
		public boolean getOnWire();
		
		public void setOnWire(boolean value);
		
		public boolean getPaymentCard();
		
		public void setPaymentCard(boolean value);
		
		public boolean getPaymentDone();
		
		public void setPaymentDone(boolean value);
		
		public boolean getEnoughMoney();
		
		public void setEnoughMoney(boolean value);
		
		public String getBeverageSelected();
		
		public void setBeverageSelected(String value);
		
		public long getTemperatureSelected();
		
		public void setTemperatureSelected(long value);
		
		public long getSizeSelected();
		
		public void setSizeSelected(long value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onUpdateSoldeRaised();
		public void onTakeBeverageRaised();
		public void onCleaningMachineRaised();
		public void onMachineReadyRaised();
		public void onBeveragePreparationRaised();
		public void onBeverageChoiceRaised();
		public void onCancelPreparationRaised();
		public void onPayByNFCRaised();
		public void onCancelTransactionRaised();
		public void onResetSlidersRaised();
		public void onValidatePaymentRaised();
		public void onTurnOnWaterHeatingRaised();
		public void onPlacePodRaised();
		public void onPlaceTeaBagRaised();
		public void onGrindGrainsRaised();
		public void onPlaceCupRaised();
		public void onPackGrainsRaised();
		public void onWaitTemperatureRaised();
		public void onFlowWaterRaised();
		public void onAddSugarRaised();
		public void onWaitingInfusionRaised();
		public void onTakeChangeRaised();
		public void onRemoveTeaBagRaised();
		public void onFlowWaterOKRaised();
		public void onSugarOKRaised();
		public void onGrainPackingOKRaised();
		public void onWaterTempOKRaised();
		public void onTeaBagOKRaised();
		public void onPodOKRaised();
		public void onGrainCrushingOKRaised();
		public void onWaterHeatingOKRaised();
		public void onCupOKRaised();
		}
	
	public SCInterface getSCInterface();
	
}
